import asyncio
import re
from playwright.async_api import Playwright, async_playwright, expect


async def run(playwright: Playwright) -> None:
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context()
    await page.goto("https://creator.xiaohongshu.com/new/home")
    await page.locator("div").filter(has_text=re.compile(r"^发布笔记$")).nth(2).click()
    await page.get_by_text("写长文").nth(1).click()
    await page.get_by_role("button", name="新的创作").click()
    await page.get_by_placeholder("输入标题").click()
    await page.get_by_placeholder("输入标题").fill("世界你好啊")
    await page.get_by_role("paragraph").click()
    await page.locator(".tiptap").fill("你好啊世界")
    await page.get_by_text("article.content =").click()
    await page.get_by_text("article.content =").click()
    await page.get_by_text("你好啊世界 self.db.add(article) self.db.commit() self.db.refresh(article) gen_log.").press("ArrowDown")
    await page.get_by_text("你好啊世界 self.db.add(article) self.db.commit() self.db.refresh(article) gen_log.").click()
    await page.locator("#web div").filter(has_text="返回5/645/64你好啊世界 self.db.add(").nth(1).click()
    await page.get_by_role("button", name="一键排版").click()
    await page.get_by_text("2 2").click()
    await page.get_by_text("5", exact=True).click()
    await page.locator(".bgGrey > div:nth-child(7)").click()
    await page.get_by_role("button", name="下一步").click()
    await page.locator("xhs-publish-btn").click()
    await page.get_by_placeholder("填写标题会有更多赞哦").click()
    await page.get_by_placeholder("填写标题会有更多赞哦").fill("")
    await page.locator("xhs-publish-btn").click()
    await page.get_by_placeholder("填写标题会有更多赞哦").click()
    await page.get_by_placeholder("填写标题会有更多赞哦").fill("世界你好")
    await page.get_by_placeholder("填写标题会有更多赞哦").press("Tab")
    await page.get_by_role("textbox").nth(1).fill("世界你好")
    await page.locator("xhs-publish-btn").click()
    await page.locator("xhs-publish-btn").click()
    await page.locator("xhs-publish-btn").click()
    await page.locator("xhs-publish-btn").click()
    await page.locator("xhs-publish-btn").click()
    await page.goto("https://creator.xiaohongshu.com/publish/publish?from=menu&target=article")
    await page.get_by_role("button", name="新的创作").click()
    await page.get_by_placeholder("输入标题").click()
    await page.get_by_placeholder("输入标题").fill("世界你好")
    await page.get_by_placeholder("输入标题").press("Tab")
    await page.get_by_role("textbox").nth(1).fill("世界")
    await page.locator(".rich-editor-content").click()
    await page.get_by_role("paragraph").click()
    await page.locator(".tiptap").fill("世界你好")
    await page.get_by_role("button", name="一键排版").click()
    await page.locator(".loading-card-new").first.click()
    await page.get_by_role("button", name="下一步").click()
    await page.locator("xhs-publish-btn").click()
    await page.get_by_role("textbox").nth(1).dblclick()
    await page.get_by_role("textbox").nth(1).fill("你好世界")
    await page.locator(".entry").click()
    await page.locator("body").set_input_files("screenshot.png")
    await page.get_by_text("#世界杯地球online").first.click()
    await page.locator("xhs-publish-btn").click()
    await page.locator(".entry").click()
    await page.locator(".mask").first.click()
    await page.locator("div:nth-child(3) > .img-container > .mask").click()
    await page.locator("div:nth-child(3) > .img-container > .mask > .close-btn > svg").click()
    await page.locator(".close-btn > svg > path").click()
    await page.locator("xhs-publish-btn").click()
    await page.locator("xhs-publish-btn").click()
    await page.get_by_text("封面预览").click()
    await page.locator("xhs-publish-btn").click()
    await page.goto("https://creator.xiaohongshu.com/publish/publish?from=menu&target=article")
    await page.close()

    # ---------------------
    await context.close()
    await browser.close()


async def main() -> None:
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())
